name: Run tests
on: [push, pull_request]
jobs:
  test:
    name: test-tasks-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: sh install.sh
      - name: Tests
        run: bun run test
